
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label buttonDebug;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.Fixed fixed8;

	private global::Gtk.Image imageController;

	private global::Gtk.Image buttonSquare;

	private global::Gtk.Image buttonX;

	private global::Gtk.Image buttonCircle;

	private global::Gtk.Image buttonTriangle;

	private global::Gtk.Image buttonStart;

	private global::Gtk.Image buttonSelect;

	private global::Gtk.Image buttonR;

	private global::Gtk.Image buttonL;

	private global::Gtk.Image buttonUp;

	private global::Gtk.Image buttonRight;

	private global::Gtk.Image buttonDown;

	private global::Gtk.Image buttonLeft;

	private global::Gtk.Image buttonLeftStick;

	private global::Gtk.Image buttonRightStick;

	private global::Gtk.Label GtkLabel;

	private global::Gtk.HBox hbox2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonDebug = new global::Gtk.Label();
		this.buttonDebug.Name = "buttonDebug";
		this.buttonDebug.LabelProp = global::Mono.Unix.Catalog.GetString("sfdfsfd");
		this.hbox1.Add(this.buttonDebug);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonDebug]));
		w1.Position = 0;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.fixed8 = new global::Gtk.Fixed();
		this.fixed8.Name = "fixed8";
		this.fixed8.HasWindow = false;
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.imageController = new global::Gtk.Image();
		this.imageController.Name = "imageController";
		this.imageController.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("DS4Display.Controller_Blank_420.png");
		this.fixed8.Add(this.imageController);
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.buttonSquare = new global::Gtk.Image();
		this.buttonSquare.Name = "buttonSquare";
		this.buttonSquare.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("DS4Display.Controller_Square.png");
		this.fixed8.Add(this.buttonSquare);
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.buttonX = new global::Gtk.Image();
		this.buttonX.Name = "buttonX";
		this.buttonX.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("DS4Display.Controller_X.png");
		this.fixed8.Add(this.buttonX);
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.buttonCircle = new global::Gtk.Image();
		this.buttonCircle.Name = "buttonCircle";
		this.buttonCircle.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("DS4Display.Controller_Circle.png");
		this.fixed8.Add(this.buttonCircle);
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.buttonTriangle = new global::Gtk.Image();
		this.buttonTriangle.Name = "buttonTriangle";
		this.buttonTriangle.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("DS4Display.Controller_Triangle.png");
		this.fixed8.Add(this.buttonTriangle);
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.buttonStart = new global::Gtk.Image();
		this.buttonStart.Name = "buttonStart";
		this.buttonStart.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-dialog-error", global::Gtk.IconSize.Menu);
		this.fixed8.Add(this.buttonStart);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed8[this.buttonStart]));
		w8.X = 250;
		w8.Y = 50;
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.buttonSelect = new global::Gtk.Image();
		this.buttonSelect.Name = "buttonSelect";
		this.buttonSelect.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-dialog-error", global::Gtk.IconSize.Menu);
		this.fixed8.Add(this.buttonSelect);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed8[this.buttonSelect]));
		w9.X = 150;
		w9.Y = 50;
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.buttonR = new global::Gtk.Image();
		this.buttonR.Name = "buttonR";
		this.buttonR.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("DS4Display.Controller_R.png");
		this.fixed8.Add(this.buttonR);
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.buttonL = new global::Gtk.Image();
		this.buttonL.Name = "buttonL";
		this.buttonL.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("DS4Display.Controller_L.png");
		this.fixed8.Add(this.buttonL);
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.buttonUp = new global::Gtk.Image();
		this.buttonUp.Name = "buttonUp";
		this.buttonUp.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("DS4Display.Controller_DPadU.png");
		this.fixed8.Add(this.buttonUp);
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.buttonRight = new global::Gtk.Image();
		this.buttonRight.Name = "buttonRight";
		this.buttonRight.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("DS4Display.Controller_DPadR.png");
		this.fixed8.Add(this.buttonRight);
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.buttonDown = new global::Gtk.Image();
		this.buttonDown.Name = "buttonDown";
		this.buttonDown.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("DS4Display.Controller_DPadD.png");
		this.fixed8.Add(this.buttonDown);
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.buttonLeft = new global::Gtk.Image();
		this.buttonLeft.Name = "buttonLeft";
		this.buttonLeft.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("DS4Display.Controller_DPadL.png");
		this.fixed8.Add(this.buttonLeft);
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.buttonLeftStick = new global::Gtk.Image();
		this.buttonLeftStick.Name = "buttonLeftStick";
		this.buttonLeftStick.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("DS4Display.Controller_LeftStick.png");
		this.fixed8.Add(this.buttonLeftStick);
		// Container child fixed8.Gtk.Fixed+FixedChild
		this.buttonRightStick = new global::Gtk.Image();
		this.buttonRightStick.Name = "buttonRightStick";
		this.buttonRightStick.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("DS4Display.Controller_RightStick.png");
		this.fixed8.Add(this.buttonRightStick);
		this.GtkAlignment.Add(this.fixed8);
		this.frame1.Add(this.GtkAlignment);
		this.GtkLabel = new global::Gtk.Label();
		this.GtkLabel.Name = "GtkLabel";
		this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>GtkFrame</b>");
		this.GtkLabel.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel;
		this.vbox1.Add(this.frame1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w21.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 486;
		this.DefaultHeight = 540;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
